exclude: '^$'
fail_fast: false
repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  sha: v1.1.1
  hooks:
    - id: autopep8-wrapper
    - id: check-added-large-files
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: flake8
    - id: trailing-whitespace

- repo: git@github.com:pre-commit/mirrors-yapf.git
  sha: v0.20.0
  hooks:
    - id: yapf
      exclude: 'migrations|settings|scripts'

- repo: git@github.com:FalconSocial/pre-commit-python-sorter.git
  sha: b57843b0b874df1d16eb0bef00b868792cb245c2
  hooks:
    - id: python-import-sorter
      args: ['--silent-overwrite']

- repo: git@github.com:humitos/mirrors-docformatter.git
  sha: v0.8
  hooks:
    - id: docformatter
